### ISSUE TITLE
Support vs_currencies besides 'usd'

### ISSUE THREAD

**Issue by tomholford** [michael-siek/coingecko-api#38]
Currently `SimplePriceParams` expects `'usd'` for `vs_currencies`. It should support any of the CG vs currencies.

**Comment by Zidious** [comment]
Hey @tomholford! 

Agreed - we used `usd` as default MVP but we should support all CG currencies. We'll get onto it as soon as possible!

**Comment by Zidious** [comment]
We have a PR open for this and once merged you should be able to install the `@next` to access the canary release. We will cut a stable release this weekend

**Comment by Zidious** [comment]
@tomholford 👋 [Canary release](https://github.com/michael-siek/coingecko-api/actions/runs/3178569479/jobs/5180198786#step:7:39) has been published. We will publish a stable release soon. 


```
npm i @crypto-coffee/coingecko-api@next
yarn add @crypto-coffee/coingecko-api@next
